spring:
  main:
    log-startup-info: false
    banner-mode: off

  sql:
    init:
      mode: always

  h2:
    console.enabled: true
    settings:
      web-allow-others: true
      trace: false

  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: 12345
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



server:
  error:
    include-message: always

logging.level.org.zalando.logbook: TRACE
