CREATE TABLE IF NOT EXISTS genre (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS rating (
  rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(255)

);

CREATE TABLE IF NOT EXISTS friendship_status (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS friendship (
  user_id BIGINT REFERENCES users (users_id),
  friend_id BIGINT REFERENCES users (users_id),
  status_id INTEGER REFERENCES friendship_status (id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    login VARCHAR(255),
    name VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS likes (
  film_id BIGINT REFERENCES films (film_id),
  user_id BIGINT REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS films (
  film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(255),
  release_date DATE,
  duration INTEGER,
  rating_id INTEGER REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS genres_films (
  film_id BIGINT REFERENCES films (film_id),
  genre_id BIGINT REFERENCES genre (genre_id)
);
